name: ci
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn
      - name: Run linters
        run: yarn lint
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn
      - name: TypeScript Build
        run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn
      - name: Start docker services
        run: yarn cli docker start
      - name: Test
        run: yarn test
